# Generated by Django 2.2.2 on 2019-07-31 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnum',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
