# Generated by Django 2.2.2 on 2019-07-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190727_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
